---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ethminer
  name: ethminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethminer
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ethminer
    spec:
      containers:
        - name: ethminer
          image: quay.io/mats16/ethminer:0.16.1
          imagePullPolicy: Always
          command: ["./ethminer"]
          args: ["--cuda", "--farm-recheck", "200", "-R", "stratum://$(ETH_WALLET).$(WORKER_NAME)@$(ETH_POOL_HOST)"]
          env:
            - name: ETH_WALLET
              value: 0xc76504780628aa38bd10bc9fc07054xxxxxxxxxx
            - name: ETH_POOL_HOST
              value: us2.ethermine.org:4444
            - name: WORKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              nvidia.com/gpu: 1
          terminationMessagePath: /dev/termination-log
